language: c
os:
  - osx
  - linux
  - windows
script:
  - cd soak
  - mkdir build
  - cd build
  - cmake ..
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then mingw32-make ; fi
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then make ; fi