os:
  - osx
  - linux
  - windows

jobs:
  include:
    - language: c
      install:
        - chmod +x ./bin/travis/compile_soak.sh 
      script:
        - ./bin/travis/compile_soak.sh 
      
    - language: cpp 
      install:
        - chmod +x ./bin/travis/compile_soak.sh 
      script:
        - ./bin/travis/compile_soak.sh 